---

- name: 'apt update && apt upgrade'
  hosts: 'ypid_apt'
  become: True

  tasks:

    - name: Upgrading system
      apt:
        upgrade: 'full'
        update_cache: True
        autoremove: True
