---

- name: Package management aware renaming of files
  collections: [ 'debops.debops' ]
  hosts: [ 'ypid_common', 'ypid_service_divert' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: ypid.divert
      tags: [ 'role::divert' ]
