---

- name: Install and manage the Mandos server
  collections: [ 'debops.debops' ]
  hosts: [ 'debops_service_mandos' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: keyring
      tags: [ 'role::keyring', 'skip::keyring', 'role::mandos' ]
      keyring__dependent_apt_keys:
        - '{{ mandos__keyring__dependent_apt_keys }}'

    - role: etc_services
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list:
        - '{{ mandos__etc_services__dependent_list }}'

    - role: ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ mandos__ferm__dependent_rules }}'

    - role: debops-contrib.mandos
      tags: [ 'role::mandos' ]
