---

- name: Install and manage the Mandos server
  hosts: [ 'debops_service_mandos' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: debops.etc_services
      tags: [ 'role::etc_services' ]
      etc_services__dependent_list:
        - '{{ mandos__etc_services__dependent_list }}'

    - role: debops.ferm
      tags: [ 'role::ferm', 'skip::ferm' ]
      ferm__dependent_rules:
        - '{{ mandos__ferm__dependent_rules }}'

    - role: debops-contrib.mandos
      tags: [ 'role::mandos' ]
