---

- name: Manage opnSense Firewall
  hosts: [ 'platform_opnsense' ]
  gather_facts: false
  become: False

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  roles:

    - role: opnsense
      tags: [ 'role::opnsense' ]
