---

- name: Common configuration for all hosts
  hosts: [ 'ypid_common' ]
  become: True

  roles:

    ## Merge with debops.rsyslog and debops.logrotate
    # - role: ypid.rsyslog
    #   tags: [ 'role::ypid.rsyslog' ]

    ## TODO: Broken?
    # - role: tersmitten.updatedb
    #   tags: [ 'role::updatedb' ]

- import_playbook: service/divert.yml
