---

- import_playbook: service_early/all.yml

- import_playbook: debops.yml
- import_playbook: ../debops-playbooks/service/debops_legacy.yml

  ## Ensure that packages are installed before debops-contrib.firejail.
- import_playbook: sys/all.yml

- import_playbook: ../debops-contrib-playbooks/service/all.yml

- import_playbook: common.yml
- import_playbook: security/all.yml
- import_playbook: net/all.yml
- import_playbook: workstation/all.yml
- import_playbook: save_ansible_facts.yml
